### PR TITLE
Page layout fixes

### LINKED ISSUE #20: Fix layout to match updated design
Link to design: https://www.figma.com/file/QgARpslF4xfNx1ZVcTlCzb/BoGaTa?node-id=411%3A2

### PR DESCRIPTION
**Pull request by TranLe2403**
This PR includes:
- update dependency versions
- App component restructure
- move search bar from TopBar component into its own implementation file, named SearchInput
- Add FilterBox and FilterSelect components
- some rework on GameItem component
- take use of ready-made components from MUI
- add/update test files for components

### CODE REVIEW

File: src/components/FilterSelect/index.tsx [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+}
+
+const FilterSelect = ({ title, data, options, setOptions }: PropsType) => {
+  const [open, setOpen] = useState<boolean>(true);
+  const onClickOptionHandler = (item: string) => {
+    const copyOptions = [...options];
+    const newArr = copyOptions.includes(item)
+      ? copyOptions.filter((option) => option !== item)
+      : copyOptions.concat(item);
+    setOptions(newArr);
```
Comment (dendimaniac) [inline src/components/FilterSelect/index.tsx:36]: The options props here don't get updated, so probably can skip the copy part

File: src/components/GameItem/index.tsx [hunk 2]
```diff
@@ -1,72 +1,44 @@
...
-`;
-
-const RatingContainer = styled.div`
-  display: flex;
-  align-items: center;
-  height: fit-content;
-  gap: 8px;
-`;
+const DEFAULT_IMG =
+  'https://socialistmodernism.com/wp-content/uploads/2017/07/placeholder-image.png';
```
Comment (dendimaniac) [inline src/components/GameItem/index.tsx:11]: Probably could move this to a helper/config class or sth

File: src/components/GameItem/index.tsx [hunk 3]
```diff
@@ -1,72 +1,44 @@
...
 
 const GameItem = ({ data }: { data: GameItemType }) => {
+  const classes = useStyles();
+  const getImageSrc = () => (data.pictures === undefined ? DEFAULT_IMG : data.pictures[0]);
```
Comment (dendimaniac) [inline src/components/GameItem/index.tsx:15]: On line 15, probably doing check using `data.pictures ? DEFAULT_IMG : data.pictures[0]` might be better, just in case it's empty array?

File: src/components/SearchInput/index.test.tsx [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+  });
+
+  it('should display search icon and it is workable', () => {
+    const searchInputElem = render(<SeachInput setSearchValue={mockSetState} />);
+    const searchIconElement = searchInputElem.getByTestId('search-icon');
+    const getIconElem = searchIconElement.firstChild as HTMLImageElement;
+
+    fireEvent.click(getIconElem);
+
+    expect(mockSetState).toBeCalledTimes(1);
```
Comment (dendimaniac) [inline src/components/SearchInput/index.test.tsx:26]: Not sure here but wouldn't putting the test-id straight onto the icon better? No need for `.firstChild`?

File: src/components/SearchInput/index.tsx [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    color: 'inherit',
+    width: '100%'
+  },
+  inputInput: {
+    padding: '8px 40px 8px 0'
+  }
+}));
+
+const SeachInput = ({ setSearchValue }: PropsType) => {
+  let search = '';
```
Comment (dendimaniac) [inline src/components/SearchInput/index.tsx:44]: Here on line 44, would putting search outside of the component better? If placed here it'd be created new every time the component re-render?

**Review by quan-dao-99 — DISMISSED** [review]
Just a few minor comments, but overall looks good 👍

**Review by quan-dao-99 — APPROVED** [review]
